%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% RARE VTR ROI ANALYSIS PIPELINE
% ANALYZES COHORT 2 OF THE PD MOUSE STUDY
% ADAPTED TO ALSO ANALYZE COHORT 1
% WRITTEN BY VG 2022
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% cohort 1
data_path_cohort0 = ['/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/170/niftis/RAREVTR_14'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/170/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/174/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/174/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/175/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/175/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/181/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/181/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/354/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/354/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/356/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/356/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/388/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/388/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/432/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/432/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/434/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/434/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/435/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/435/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/436/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/436/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/441/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/441/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/442/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/442/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/444/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/444/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/446/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/446/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/449/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/449/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/476/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/476/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/477/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_0/477/niftis/RAREVTR_19'];



data_path_cohort1 = ['/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/131/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/131/niftis/RAREVTR_25'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/155/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/155/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/261/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/261/niftis/RAREVTR_18'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/263/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/263/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/270/niftis/RAREVTR_25'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/270/niftis/RAREVTR_31'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/271/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/271/niftis/RAREVTR_21'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/274/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/274/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/275/niftis/RAREVTR_13'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/275/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/276/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/276/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/428/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/428/niftis/RAREVTR_18'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/433/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/433/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/435/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/435/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/438/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/438/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/440/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/440/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/444/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/444/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/445/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/445/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/449/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/449/niftis/RAREVTR_23'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/453/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/453/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/464/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/464/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/508/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/508/niftis/RAREVTR_26'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/509/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/509/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/513/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/513/niftis/RAREVTR_21'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/514/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/514/niftis/RAREVTR_23'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/519/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/519/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/535/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/535/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/536/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/536/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/538/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/538/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/542/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/542/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/543/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/543/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/544/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/544/niftis/RAREVTR_21'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/592/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/592/niftis/RAREVTR_25'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/593/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/593/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/594/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/594/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/664/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/664/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/665/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/665/niftis/RAREVTR_23'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/674/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/674/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/676/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/676/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/677/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/677/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/678/niftis/RAREVTR_10'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/678/niftis/RAREVTR_21'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/681/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_1/681/niftis/RAREVTR_19'];


data_path_cohort2 = ['/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/698/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/698/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/702/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/702/niftis/RAREVTR_22'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/703/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/703/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/706/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/706/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/707/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/707/niftis/RAREVTR_24'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/711/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/711/niftis/RAREVTR_21'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/713/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/713/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/725/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/725/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/726/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/726/niftis/RAREVTR_17'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/727/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/727/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/729/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/729/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/731/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/731/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/733/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/733/niftis/RAREVTR_28'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/734/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/734/niftis/RAREVTR_24'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/735/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/735/niftis/RAREVTR_23'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/777/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/777/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/778/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/778/niftis/RAREVTR_23'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/779/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/779/niftis/RAREVTR_24'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/782/niftis/RAREVTR_29'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/782/niftis/RAREVTR_39'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/784/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/784/niftis/RAREVTR_30'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/788/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/788/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/812/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/812/niftis/RAREVTR_20'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/817/niftis/RAREVTR_13'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/817/niftis/RAREVTR_24'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/818/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/818/niftis/RAREVTR_21'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/821/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/821/niftis/RAREVTR_24'; ... 
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/825/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/825/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/833/niftis/RAREVTR_14'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/833/niftis/RAREVTR_18'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/834/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/834/niftis/RAREVTR_19'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/838/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/838/niftis/RAREVTR_16'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/839/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/839/niftis/RAREVTR_22'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/843/niftis/RAREVTR_15'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/843/niftis/RAREVTR_24'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/845/niftis/RAREVTR_12'; ...
                     '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2/845/niftis/RAREVTR_21'];
                 
                 
%% Run the analysis       

% add niftitools and EMD toolbox to path
addpath(genpath('/data/rudko/vgrouza/invivomouse/niftitools'));
addpath(genpath('/data/rudko/vgrouza/invivomouse/emd-2005-02'));
addpath(genpath('/data/rudko/vgrouza/invivomouse/jsdiv'));

allSubjectPars = [];
allSubjectDir = '/data/rudko/vgrouza/invivomouse/pddata/data/cohort_2';
allSubjectFileName = 't1_Cohort2SubjectParsBS.csv';
currDataPath = data_path_cohort2;
cohort_num = 2;

for i = 1:2:size(currDataPath, 1)
% Don't forget to change the cohort!
    currSubjectPars = struct2table(run_analysis(currDataPath(i,:), currDataPath(i+1,:), cohort_num));
    allSubjectPars = [allSubjectPars; currSubjectPars];  
end
writetable(allSubjectPars, fullfile(allSubjectDir, allSubjectFileName), 'delimiter',',');
fprintf('Completed Analysis of %d subjects. \n', size(currDataPath, 1)/2);
                 
%% MAIN ANALYSIS FUNCTION                

function currSubjectPars = run_analysis(input_path_pre, input_path_post, cohort_number)

    % get subject summary information
    currSubjectPars = parse_subject_parameters(input_path_pre, cohort_number);
    currSubjectPars.PathToPre = input_path_pre;                                   
    currSubjectPars.PathToPost = input_path_post;
    fprintf('Processing subject %d... \n', currSubjectPars.ID);
        
    % get T1 distributions within ROIS pre- and post-ca injection
    T1HistogramsPre = segment_t1_map(input_path_pre);
    T1HistogramsPost = segment_t1_map(input_path_post);
    
    % compute wasserstein/earth mover's distance for each roi                           
    
    % STRIATUM
    % Simple Mean
    currSubjectPars.T1pre_striatum = T1HistogramsPre.T1_Striatum;
    currSubjectPars.T1post_striatum = T1HistogramsPost.T1_Striatum;
    
      
    % EMD
    [~, currSubjectPars.EMDstriatum] = emd(T1HistogramsPre.BinSupport', ...
                                           T1HistogramsPost.BinSupport', ...
                                           T1HistogramsPre.Striatum', ...
                                           T1HistogramsPost.Striatum', ...
                                           @gdf);     
    % Z value
    [p, h, stats] = ranksum(T1HistogramsPre.ROI_Striatum, T1HistogramsPost.ROI_Striatum, ...
                            'alpha',0.01, ...
                            'tail','right');
    currSubjectPars.zval_striatum = stats.zval;  


    % T Test
    [h, p, ~, stats_t] = ttest2(T1HistogramsPre.ROI_Striatum, T1HistogramsPost.ROI_Striatum, 'Vartype','unequal')    
    
    % THALAMUS
    % Simple Mean
    currSubjectPars.T1pre_thalamus = T1HistogramsPre.T1_Thalamus;
    currSubjectPars.T1post_thalamus = T1HistogramsPost.T1_Thalamus;
    
   
    % EMD
    [~, currSubjectPars.EMDthalamus] = emd(T1HistogramsPre.BinSupport', ...
                                           T1HistogramsPost.BinSupport', ...
                                           T1HistogramsPre.Thalamus', ...
                                           T1HistogramsPost.Thalamus', ...
                                           @gdf);   
    % Z value
    [p, h, stats] = ranksum(T1HistogramsPre.ROI_Thalamus, T1HistogramsPost.ROI_Thalamus, ...
                            'alpha',0.01, ...
                            'tail','right');
    currSubjectPars.zval_thalamus = stats.zval;  


    % T Test
    [h, p, ~, stats_t] = ttest2(T1HistogramsPre.ROI_Thalamus, T1HistogramsPost.ROI_Thalamus, 'Vartype','unequal')
    
    % PRIMARY SSC
    % Simple Mean
    currSubjectPars.T1pre_pssc = T1HistogramsPre.T1_PrimarySSC;
    currSubjectPars.T1post_pssc = T1HistogramsPost.T1_PrimarySSC;
    
       
    % EMD
    [~, currSubjectPars.EMDpssc] = emd(T1HistogramsPre.BinSupport', ...
                                           T1HistogramsPost.BinSupport', ...
                                           T1HistogramsPre.PrimarySSC', ...
                                           T1HistogramsPost.PrimarySSC', ...
                                           @gdf);   
    % Z value
    [p, h, stats] = ranksum(T1HistogramsPre.ROI_PrimarySSC, T1HistogramsPost.ROI_PrimarySSC, ...
                            'alpha',0.01, ...
                            'tail','right');
    currSubjectPars.zval_pssc = stats.zval;  

    % T Test
    [h, p, ~, stats_t] = ttest2(T1HistogramsPre.ROI_PrimarySSC, T1HistogramsPost.ROI_PrimarySSC, 'Vartype','unequal')
                                       
    % DENTATE GYRUS
    % Simple Mean
    currSubjectPars.T1pre_dg = T1HistogramsPre.T1_DentateGyrus;
    currSubjectPars.T1post_dg = T1HistogramsPost.T1_DentateGyrus;
    
                                                 
    % EMD
    [~, currSubjectPars.EMDdg] = emd(T1HistogramsPre.BinSupport', ...
                                     T1HistogramsPost.BinSupport', ...
                                     T1HistogramsPre.DentateGyrus', ...
                                     T1HistogramsPost.DentateGyrus', ...
                                     @gdf);    
    % Z value
    [p, h, stats] = ranksum(T1HistogramsPre.ROI_DentateGyrus, T1HistogramsPost.ROI_DentateGyrus, ...
                            'alpha',0.01, ...
                            'tail','right');
    currSubjectPars.zval_dg = stats.zval;
    
    % T Test
    [h, p, ~, stats_t] = ttest2(T1HistogramsPre.ROI_DentateGyrus, T1HistogramsPost.ROI_DentateGyrus, 'Vartype','unequal')
                                 
    
    % generate a summary figure
    % generate_figure(currSubjectPars, T1HistogramsPre, T1HistogramsPost);                                       
    %generate_figure_bs(currSubjectPars, T1HistogramsPre, T1HistogramsPost);                                       
                                       
    % save Pars and Histograms as .csv
    currSubjectPars = orderfields(currSubjectPars, [1 2 3 4 5 6 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 7 8 9]);
    fooTable = struct2table(currSubjectPars);
    writetable(fooTable, fullfile(currSubjectPars.PathToStudy, 't1_SubjectPars.csv'), 'delimiter',',');
    disp('Done.')
end

        
%% SUPPORTING FUNCTIONS        
function [] = generate_figure(currSubjectPars, T1HistogramsPre, T1HistogramsPost)

    close all;
    curr_fig = figure(1); 
    set(gcf, 'Color', 'w', 'Position',[0 0 1200 800]);
    sgtitle(sprintf('VTR T_1 Summary for Subject %s %d', currSubjectPars.Genotype, currSubjectPars.ID), 'FontWeight', 'b'); 

    subplot(2,2,1); hold on;
        % Thalamus
        t1mean_pre = T1HistogramsPre.T1_Thalamus;
        t1mean_post = T1HistogramsPost.T1_Thalamus;        
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.Thalamus, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.Thalamus, 'r', 'FaceAlpha', 0.5);
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDthalamus));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(i). Thalamus');
        
    subplot(2,2,2); hold on;
        % Striatum
        t1mean_pre = T1HistogramsPre.T1_Striatum;
        t1mean_post = T1HistogramsPost.T1_Striatum;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.Striatum, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.Striatum, 'r', 'FaceAlpha', 0.5);        
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDstriatum));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(ii). Striatum');
        
    subplot(2,2,3); hold on;
        % Primary Somatosensory Cortex
        t1mean_pre = T1HistogramsPre.T1_PrimarySSC;
        t1mean_post = T1HistogramsPost.T1_PrimarySSC;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.PrimarySSC, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.PrimarySSC, 'r', 'FaceAlpha', 0.5);       
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDpssc));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(iii). Primary SSC');
        
    subplot(2,2,4); hold on;
        % Dentate Gyrus
        t1mean_pre = T1HistogramsPre.T1_DentateGyrus;
        t1mean_post = T1HistogramsPost.T1_DentateGyrus;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.DentateGyrus, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.DentateGyrus, 'r', 'FaceAlpha', 0.5); 
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDdg));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(iv). Dentate Gyrus');
    for i = 1:4
        subplot(2,2,i);
            set(gca, 'LineWidth', 2, 'FontWeight', 'b', 'FontSize', 10);
            xlabel('T_1 (msec)'); ylabel('Density');
            xlim([1500, 3000]); ylim([0, 0.2]);
            legend('Pre-CA', 'Post-CA', 'Location', 'NorthEast')
    end
    
    % save figure to main Bruker study directory
    if currSubjectPars.Infected == 0 && currSubjectPars.Timepoint > 0
        fig_string = sprintf('%d_%s_noninfected_t1_summary.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Infected == 1
        fig_string = sprintf('%d_%s_infected_t1_summary.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Timepoint == -1
        fig_string = sprintf('%d_%s_ptx_treated_t1_summary.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Timepoint == 0
        fig_string = sprintf('%d_%s_ptx_control_t1_summary.png', ...
                                 currSubjectPars.ID, ...
                                 currSubjectPars.Genotype);  
                         
    end    
    saveas(curr_fig, fullfile(fileparts(currSubjectPars.PathToStudy), fig_string));        
    
end    



function [] = generate_figure_bs(currSubjectPars, T1HistogramsPre, T1HistogramsPost)

    curr_fig = figure(2); 
    set(gcf, 'Color', 'w', 'Position',[0 0 1200 800]);
    sgtitle(sprintf('VTR T_1 Summary for Subject %s %d', currSubjectPars.Genotype, currSubjectPars.ID), 'FontWeight', 'b'); 

    subplot(2,2,1); hold on;
        % Thalamus
        t1mean_pre = T1HistogramsPre.T1_Thalamus;
        t1mean_post = T1HistogramsPost.T1_Thalamus;        
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.ThalamusBS, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.ThalamusBS, 'r', 'FaceAlpha', 0.5);
        
        %[h, p] = ttest2(T1HistogramsPre.ThalamusBS, T1HistogramsPost.ThalamusBS,  'alpha', 0.05, 'Vartype','unequal')
        [p, h, stats] = ranksum(T1HistogramsPre.ROI_Thalamus, T1HistogramsPost.ROI_Thalamus, 'alpha',0.01,...
'tail','right')
        
        
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDthalamus));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(i). Thalamus');
        
    subplot(2,2,2); hold on;
        % Striatum
        t1mean_pre = T1HistogramsPre.T1_Striatum;
        t1mean_post = T1HistogramsPost.T1_Striatum;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.StriatumBS, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.StriatumBS, 'r', 'FaceAlpha', 0.5);
        
%        [h, p] = ttest2(T1HistogramsPre.StriatumBS, T1HistogramsPost.StriatumBS,  'alpha', 0.05, 'Vartype','unequal')
        [p, h, stats] = ranksum(T1HistogramsPre.ROI_Striatum, T1HistogramsPost.ROI_Striatum, 'alpha',0.01,...
'tail','right')
        
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDstriatum));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(ii). Striatum');
        
    subplot(2,2,3); hold on;
        % Primary Somatosensory Cortex
        t1mean_pre = T1HistogramsPre.T1_PrimarySSC;
        t1mean_post = T1HistogramsPost.T1_PrimarySSC;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.PrimarySSCBS, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.PrimarySSCBS, 'r', 'FaceAlpha', 0.5);       
        
        %[h, p] = ttest2(T1HistogramsPre.PrimarySSCBS, T1HistogramsPost.PrimarySSCBS,  'alpha', 0.05, 'Vartype','unequal')
        [p, h, stats] = ranksum(T1HistogramsPre.ROI_PrimarySSC, T1HistogramsPost.ROI_PrimarySSC,'alpha',0.01,...
'tail','right')
        
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDpssc));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(iii). Primary SSC');
        
    subplot(2,2,4); hold on;
        % Dentate Gyrus
        t1mean_pre = T1HistogramsPre.T1_DentateGyrus;
        t1mean_post = T1HistogramsPost.T1_DentateGyrus;
        bar(T1HistogramsPre.BinSupport, T1HistogramsPre.DentateGyrusBS, 'FaceColor', [0.8 0.8 0.8], 'FaceAlpha', 1);
        bar(T1HistogramsPost.BinSupport, T1HistogramsPost.DentateGyrusBS, 'r', 'FaceAlpha', 0.5); 

        %[h, p] = ttest2(T1HistogramsPre.DentateGyrusBS, T1HistogramsPost.DentateGyrusBS,  'alpha', 0.05, 'Vartype','unequal')
        [p, h, stats] = ranksum(T1HistogramsPre.ROI_DentateGyrus, T1HistogramsPost.ROI_DentateGyrus, 'alpha',0.01,...
'tail','right')
        
        text(1750, 0.15, sprintf('EMD = %2.1f', currSubjectPars.EMDdg));
        text(2500, 0.1, sprintf('T1_{pre} = %2.1f msec', t1mean_pre))
        text(1600, 0.1, sprintf('T1_{post} = %2.1f msec', t1mean_post))
        title('(iv). Dentate Gyrus');
    for i = 1:4
        subplot(2,2,i);
            set(gca, 'LineWidth', 2, 'FontWeight', 'b', 'FontSize', 10);
            xlabel('T_1 (msec)'); ylabel('Density');
            xlim([1500, 3000]); ylim([0, 0.2]);
            legend('Pre-CA', 'Post-CA', 'Location', 'NorthEast')
    end
    
    % save figure to main Bruker study directory
    if currSubjectPars.Infected == 0 && currSubjectPars.Timepoint > 0
        fig_string = sprintf('%d_%s_noninfected_t1_summaryBS.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Infected == 1
        fig_string = sprintf('%d_%s_infected_t1_summaryBS.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Timepoint == -1
        fig_string = sprintf('%d_%s_ptx_treated_t1_summaryBS.png', ...
                             currSubjectPars.ID, ...
                             currSubjectPars.Genotype);
    elseif currSubjectPars.Timepoint == 0
        fig_string = sprintf('%d_%s_ptx_control_t1_summaryBS.png', ...
                                 currSubjectPars.ID, ...
                                 currSubjectPars.Genotype);  
                         
    end    
    saveas(curr_fig, fullfile(fileparts(currSubjectPars.PathToStudy), fig_string));        
    
end    
    



function T1Histograms = segment_t1_map(input_path)
% segment the T1 map using DSURQE atlas labels warped to native space

    % load t1 map and labels
    t1map = load_nii(fullfile(input_path, 't1_map_corrected.nii.gz')).img;
    labels = round(load_nii(fullfile(input_path, 'labels_inv.nii.gz')).img);    

    % specify bin widths for t1 histograms
    bin_width = 25;
    bin_edges = 1500:bin_width:3000;
    bin_support = (bin_edges(1)+bin_width/2):bin_width:(bin_edges(end)-bin_width/2);

    % set roi labels based on DSURQE atlas
    thalamus_idx  = [204, 4];
    striatum_idx = [7, 17];
    primary_ssc_idx = [111, 280];
    dentate_gyrus_idx = 326:331;

    % pur roi labels into a cell so we can cycle through them
    roi_cell{1} = thalamus_idx;
    roi_cell{2} = striatum_idx;
    roi_cell{3} = primary_ssc_idx;
    roi_cell{4} = dentate_gyrus_idx;

    % cycle through rois
    bin_density_matrix = zeros(length(roi_cell), length(bin_support));
    bin_density_bs_matrix = zeros(length(roi_cell), length(bin_support));
    t1_mean_matrix = zeros(length(roi_cell), 1);
    NBTSTRP = 1000;
    for i = 1:length(roi_cell)
        roi_nums = roi_cell{i};
        % segment roi within the whole t1 map
        roi_labels = zeros(size(labels));
        for j = 1:length(roi_nums)
            roi_labels = roi_labels + (labels == roi_nums(j));            
        end
        % bin the t1 values into predefined histogram support    
        t1_roi = rmoutliers(t1map(roi_labels > 0));
        [bin_density, ~] = histcounts(t1_roi, ...
                                     bin_edges, ...
                                     'Normalization', 'probability');    
        bin_density_matrix(i, :) = bin_density;
        
        t1_mean_matrix(i, 1) = mean(t1_roi);
        
        for j = 1:NBTSTRP
            [bin_density_bs(i,:), ~] = histcounts(datasample(t1_roi, NBTSTRP), ...
                                         bin_edges, ...
                                         'Normalization', 'probability');    
        end
        bin_density_bs = mean(bin_density_bs, 1);     
        
        bin_density_bs_matrix(i, :) = bin_density_bs;
        
        if i == 1
            T1Histograms.ROI_Thalamus = t1_roi;
        elseif i == 2
            T1Histograms.ROI_Striatum = t1_roi;
        elseif i == 3
            T1Histograms.ROI_PrimarySSC = t1_roi;
        elseif i == 4
            T1Histograms.ROI_DentateGyrus = t1_roi;
        end
    end
    
    T1Histograms.BinSupport = bin_support;
    T1Histograms.Thalamus = bin_density_matrix(1,:);
    T1Histograms.ThalamusBS = bin_density_bs_matrix(1,:);
    T1Histograms.T1_Thalamus = t1_mean_matrix(1,1);
        
    T1Histograms.Striatum = bin_density_matrix(2,:);
    T1Histograms.StriatumBS = bin_density_bs_matrix(2,:);
    T1Histograms.T1_Striatum = t1_mean_matrix(2,1);
    
    
    T1Histograms.PrimarySSC = bin_density_matrix(3,:);
    T1Histograms.PrimarySSCBS = bin_density_bs_matrix(3,:);
    T1Histograms.T1_PrimarySSC = t1_mean_matrix(3,1);
        
    T1Histograms.DentateGyrus = bin_density_matrix(4,:);
    T1Histograms.DentateGyrusBS = bin_density_bs_matrix(4,:);
    T1Histograms.T1_DentateGyrus = t1_mean_matrix(4,1);
    

end


function SubjectPars = parse_subject_parameters(input_path_pre, cohort_number)
% gets summary information about the current subject
    
    % aggregate identifying subject parameters from Bruker "./subject" file
    pathparts = strsplit(input_path_pre,filesep);
    study_path = strcat('/', fullfile(pathparts{1:end-2}));

    % load subject file into string array
    fid = fopen(fullfile(study_path, 'subject'),'r');
    subject_file = fread(fid,Inf,'*char');
    fclose(fid);
    clear fid;

    % parse subject file indices for subject name
    index1 = strfind(subject_file','##$SUBJECT_name=(<>, <') + length('##$SUBJECT_name=(<>, <');
    index2temp = strfind(subject_file', '>');
    index2 = index2temp(find(index2temp > index1, 1));
    subject_name = lower(subject_file(index1:index2-1)');
    clear index1 index2 index2temp;

    % subject ID
    subject_id = str2double(pathparts{end-2});

    % subject sex
    index1 = strfind(subject_file','##$SUBJECT_sex=( 8 )') + length('##$SUBJECT_sex=( 8 )') + 2;
    index2temp = strfind(subject_file', '>');
    index2 = index2temp(find(index2temp > index1, 1));
    subject_sex_str = lower(subject_file(index1:index2-1)');
    if contains(subject_sex_str, 'female')
        subject_sex = 'F';
    else
        subject_sex = 'M';
    end    
    clear index1 index2 index2temp;

    % genotype
    if contains(subject_name, 'ko')
        genotype = 'KO';
    elseif contains(subject_name, 'wt')
        genotype = 'WT';
    else    
        genotype = 'WT';
    end

    % InfectionStatus
    if contains(subject_name, 'non')
        infected = false;
    elseif contains(subject_name, 'control')
        infected = false;
    elseif contains(subject_name, 'ptx')
        infected = false;
    else
        infected = true;    
    end    

    % TimePoint
    if contains(subject_name, 'day13')
        timepoint = 1;
    elseif contains(subject_name, 'day26')
        timepoint = 2;
    elseif contains(subject_name, 'control')
        timepoint = 0;
    elseif contains(subject_name, 'ptx')
        timepoint = -1;
    else    
        timepoint = 1;
    end
    
    % summarize into a data structure
    SubjectPars.ID = subject_id;
    SubjectPars.Sex = subject_sex;
    SubjectPars.Genotype = genotype;
    SubjectPars.Infected = infected;
    SubjectPars.Timepoint = timepoint;
    SubjectPars.Cohort = cohort_number;
    SubjectPars.PathToStudy = study_path;
    
end
                
